### ISSUE TITLE
Do Alternative Render Packs Exist?

### ISSUE THREAD

**Issue by opticyclic** [kettek/open-markup-editor#35]
I am using the AppImage on Ubuntu and it has the Default and GitHub built in [render packs](https://github.com/kettek/open-markup-editor/tree/master/packs/render-packs).

There is some documentation about creating packs [here](https://github.com/kettek/open-markup-editor/blob/master/docs/render-packs.md).

However, I couldn't find any. Do any exist?

I was mainly looking for alternatives because **bold** displays in the default render pack but not in the GitHub pack.

And urls such as https://github.com/kettek/open-markup-editor are not rendered as links in either.

**Comment by kettek** [comment]
One is available @ https://github.com/kettek/ome-rp-dnd.kettek.net and other in a private repo.

You can also inspect the default ones [here](https://github.com/kettek/open-markup-editor/tree/master/packs/render-packs).

Making your own render pack is a matter of creating a "tar.gz" file of a directory containing the render pack (such as ome-rp-default) and giving it an appropriate name (such as ome-rp-default-1.0.0.tgz).

There is no auto-linkifying for non-markdown URLs, but that could be implemented within OME's settings page. Additionally, I suspect that the GitHub pack is due for an update to its style dependencies.

**Comment by kettek** [comment]
**bold** displays correctly in the GitHub pack for me, using the ```**bold**``` syntax.

**Comment by kettek** [comment]
Hmm, probably a problem with version differences. I'll make .AppImage builds for OME 3.0.0 ASAP, as that will likely remedy the situation.

**Comment by kettek** [comment]
Updated the 3.0.0 release to have a proper .AppImage: https://github.com/kettek/open-markup-editor/releases/tag/v3.0.0

Let me know if that changes anything.

**Comment by kettek** [comment]
Closing since this is presumably resolved.

**Comment by opticyclic** [comment]
That did help. Thanks for responding so quickly.
